version: "3.8"

services:
  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./videos:/usr/share/nginx/html/videos:ro
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # desactiva autenticación por API key
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: unless-stopped

volumes:
  esdata:
